{{- range $kafkaId := until (.Values.kafkaReplica|int) }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: {{ $.Values.zkKafkaNamespace }}
  name: {{ $.Values.kafkaName }}{{ $kafkaId }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
       app: hyperledger
       role: kafka
       kafka-id: {{ $.Values.kafkaName }}{{ $kafkaId }}
    spec:
      containers:
        - name: {{ $.Values.kafkaName }}{{ $kafkaId }}
          image: hyperledger/fabric-kafka:latest
          env:
            - name: KAFKA_MESSAGE_MAX_BYTES
              value: "103809024"
            - name: KAFKA_REPLICA_FETCH_MAX_BYTES
              value: "103809024"
            - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
              value: "false"
            - name: KAFKA_BROKER_ID
              value: {{ $kafkaId|quote }}
            - name: KAFKA_MIN_INSYNC_REPLICAS
              value: "2"
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{ $.Values.kafkaZkConnect|quote }}
            # KAFKA_ADVERTISED_HOST_NAME must be set,it can make orderer connect kafka
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "{{ $.Values.kafkaName }}{{ $kafkaId }}.{{ $.Values.zkKafkaNamespace }}"
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kafka-logs/data"
            - name: KAFKA_LOG_DIR
              value: "/tmp/kafka-logs/data"
          volumeMounts:
            - mountPath: /tmp/kafka-logs
              name: zk-kafka
              subPath: data/kafka{{ $kafkaId }}
      volumes:
        - name: zk-kafka
          persistentVolumeClaim:
            claimName: zk-kafka-pvc
---
apiVersion: v1
kind: Service
metadata:
   namespace: {{ $.Values.zkKafkaNamespace }}
   name: {{ $.Values.kafkaName }}{{ $kafkaId }}
spec:
 selector:
   app: hyperledger
   role: kafka
   kafka-id: {{ $.Values.kafkaName }}{{ $kafkaId }}
 clusterIP: None
 ports:
   - name: kafka-port1
     protocol: TCP
     port: 9092

   - name: kafka-port2
     protocol: TCP
     port: 9093
---
{{- end }}